[package]
name = "lorenz"
version = "0.1.0"
authors = ["Atul Varma <varmaa@gmail.com>"]
edition = "2018"

[dependencies]
kiss3d = "0.19.0"
nalgebra = "0.18.0"
stdweb = "0.4.16"

[dependencies.rand]
version = "0.6.5"
features = ["stdweb"]
